# Generated by Django 5.2.11 on 2026-03-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='monster_type',
            field=models.CharField(choices=[('slime', 'スライム'), ('dragon', 'ドラゴン'), ('dino', '恐竜')], default='slime', max_length=20),
        ),
    ]
