# Generated by Django 5.2.11 on 2026-03-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_monster_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='monster_type',
            field=models.CharField(choices=[('bird', '雷鳥'), ('dragon', 'ドラゴン'), ('dino', '恐竜')], default='slime', max_length=20),
        ),
    ]
