# Generated by Django 5.2.11 on 2026-03-24 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_monster_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='monster_selected',
            field=models.BooleanField(default=False),
        ),
    ]
