# Generated by Django 5.2.11 on 2026-07-14 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_monster_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('trainee', '受講生'), ('instructor', '講師'), ('admin', '管理者')], default='', max_length=20, verbose_name='役割'),
        ),
    ]
