# Generated by Django 5.2.11 on 2026-07-14 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.CharField(max_length=10, unique=True, verbose_name='章番号')),
                ('title', models.CharField(max_length=200, verbose_name='章タイトル')),
                ('estimated_days', models.PositiveIntegerField(verbose_name='想定日数')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'カリキュラム章',
                'verbose_name_plural': 'カリキュラム章',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TraineeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', '未受講'), ('in_progress', '受講中'), ('completed', '完了')], default='not_started', max_length=20, verbose_name='ステータス')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='学習開始日')),
                ('expected_end_date', models.DateField(blank=True, null=True, verbose_name='完了予定日')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentoring_trainees', to=settings.AUTH_USER_MODEL, verbose_name='担当メンバー')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainee_profile', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '受講生プロフィール',
                'verbose_name_plural': '受講生プロフィール',
            },
        ),
        migrations.CreateModel(
            name='CurriculumItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(max_length=10, verbose_name='項目番号')),
                ('title', models.CharField(max_length=200, verbose_name='項目名')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='curriculum.curriculumchapter', verbose_name='章')),
            ],
            options={
                'verbose_name': 'カリキュラム項目',
                'verbose_name_plural': 'カリキュラム項目',
                'ordering': ['order'],
                'unique_together': {('chapter', 'item_number')},
            },
        ),
        migrations.CreateModel(
            name='ChapterProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='完了フラグ')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完了日時')),
                ('total_minutes', models.PositiveIntegerField(default=0, verbose_name='累計学習時間（分）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='curriculum.curriculumchapter', verbose_name='章')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_progresses', to='curriculum.traineeprofile', verbose_name='受講生')),
            ],
            options={
                'verbose_name': '章別進捗',
                'verbose_name_plural': '章別進捗',
                'unique_together': {('trainee', 'chapter')},
            },
        ),
    ]
