# Generated by Claude on 2026-07-14
# 要件定義書 v3.3 5-4「カリキュラムマスタデータ」の初期登録データ

from django.db import migrations

CURRICULUM_DATA = [
    {
        'chapter_number': '00',
        'title': 'はじめに',
        'estimated_days': 0,
        'items': [],
    },
    {
        'chapter_number': '01',
        'title': 'IT基礎知識',
        'estimated_days': 2,
        'items': [
            ('01', 'コンピュータとプログラムの仕組み'),
            ('02', '文字コードとファイルの基礎'),
            ('03', '研修での管理方法'),
        ],
    },
    {
        'chapter_number': '02',
        'title': '開発環境構築',
        'estimated_days': 2,
        'items': [
            ('01', 'VS Codeのインストールと基本操作'),
            ('02', '仮想環境とパッケージ管理'),
        ],
    },
    {
        'chapter_number': '03',
        'title': 'Git基礎',
        'estimated_days': 2,
        'items': [
            ('01', 'バージョン管理とGitの基本'),
            ('02', 'GitHubとリモートリポジトリ'),
            ('03', 'ブランチ操作'),
            ('04', 'Pull Requestと課題提出'),
            ('05', 'コンフリクト解決'),
            ('06', '実践演習（Git連携を実際に体験する）'),
            ('07', '発展演習（マージ・バージョン管理を体験する）'),
            ('08', '補足：GUIツールでのGit操作'),
        ],
    },
    {
        'chapter_number': '04',
        'title': 'Web開発の基礎知識',
        'estimated_days': 1,
        'items': [
            ('01', 'HTTPとWebの仕組み'),
        ],
    },
    {
        'chapter_number': '05',
        'title': 'SQLとデータベース基礎',
        'estimated_days': 2,
        'items': [
            ('01', 'データベースの基本概念'),
        ],
    },
    {
        'chapter_number': '06',
        'title': 'Python基礎',
        'estimated_days': 5,
        'items': [
            ('00', 'はじめに'),
            ('01', '変数・型・演算'),
            ('02', '文字列操作'),
            ('03', 'データ構造（リスト・辞書）'),
            ('04', '条件分岐と繰り返し'),
            ('05', '関数'),
            ('06', 'ファイル操作'),
            ('07', '例外処理と安全なコード'),
        ],
    },
    {
        'chapter_number': '07',
        'title': 'アプリ制作①',
        'estimated_days': 14,
        'items': [
            ('01', '要件定義とデータ構造の設計'),
            ('02', 'CLIでの基本機能実装'),
            ('03', 'ファイル操作によるデータの永続化'),
            ('04', 'HTMLテンプレートへのデータ組み込み'),
            ('05', 'テスト実行・リファクタリング'),
        ],
    },
    {
        'chapter_number': '08',
        'title': 'Python応用',
        'estimated_days': 7,
        'items': [
            ('01', '例外処理と型ヒント'),
            ('02', 'モジュール分割と標準ライブラリ'),
            ('03', '既存コードの読解と実装'),
            ('04', '単元総合テスト'),
            ('05', 'セキュリティ基礎'),
        ],
    },
    {
        'chapter_number': '09',
        'title': 'PythonWeb開発（FastAPI）',
        'estimated_days': 21,
        'items': [
            ('01', 'WebAPIとは・全体像の理解'),
            ('02', 'FastAPIのセットアップと最初のAPI'),
            ('03', 'Pydanticによるデータ検証'),
            ('04', 'SQLAlchemyとデータベース連携'),
            ('05', 'ルーティングとアーキテクチャ設計'),
            ('06', 'JWT認証の実装'),
            ('07', '単元総合テスト'),
        ],
    },
    {
        'chapter_number': '10',
        'title': 'テスト',
        'estimated_days': 7,
        'items': [
            ('01', '基本概念と導入'),
            ('02', '正常系・異常系のテスト設計'),
            ('03', 'parametrizeを用いた網羅的テスト'),
            ('04', 'fixtureを用いた前準備'),
            ('05', '関数・ロジック単位の実装演習'),
            ('06', '単元総合テスト'),
        ],
    },
    {
        'chapter_number': '11',
        'title': 'Docker',
        'estimated_days': 3,
        'items': [
            ('01', 'コンテナとDockerの基礎'),
            ('02', 'Dockerfileを書いてイメージを作る'),
            ('03', 'Docker Composeで複数サービスを管理する'),
            ('04', 'データの永続化とよくあるエラー'),
            ('05', '確認テスト'),
        ],
    },
    {
        'chapter_number': '12',
        'title': 'アプリ制作②',
        'estimated_days': 14,
        'items': [
            ('00-1', 'フロントエンド概要'),
            ('00-2', '開発環境の準備'),
            ('01', '全体像とゴールの確認'),
            ('02', 'データベース設計とDocker環境の構築'),
            ('03', 'FastAPIによるタスクCRUD APIの実装'),
            ('04', 'Pydanticによる入力検証'),
            ('05', 'フロントエンドとの接続確認'),
        ],
    },
    {
        'chapter_number': '13',
        'title': '実務相当演習',
        'estimated_days': 10,
        'items': [
            ('01', '演習の概要と設計書の読み方'),
            ('02', 'データベース設計とモデルの実装'),
            ('03', 'タスク管理APIの実装'),
            ('04', '認証・JWT・権限管理の実装'),
            ('05', 'pytestによるテスト'),
            ('06', '障害対応（IMP-001）'),
        ],
    },
]


def seed_curriculum(apps, schema_editor):
    CurriculumChapter = apps.get_model('curriculum', 'CurriculumChapter')
    CurriculumItem = apps.get_model('curriculum', 'CurriculumItem')

    for order, chapter_data in enumerate(CURRICULUM_DATA):
        chapter, _ = CurriculumChapter.objects.get_or_create(
            chapter_number=chapter_data['chapter_number'],
            defaults={
                'title': chapter_data['title'],
                'estimated_days': chapter_data['estimated_days'],
                'order': order,
            },
        )
        for item_order, (item_number, item_title) in enumerate(chapter_data['items']):
            CurriculumItem.objects.get_or_create(
                chapter=chapter,
                item_number=item_number,
                defaults={'title': item_title, 'order': item_order},
            )


def remove_curriculum_seed(apps, schema_editor):
    CurriculumChapter = apps.get_model('curriculum', 'CurriculumChapter')
    chapter_numbers = [c['chapter_number'] for c in CURRICULUM_DATA]
    CurriculumChapter.objects.filter(chapter_number__in=chapter_numbers).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_curriculum, remove_curriculum_seed),
    ]
