# Generated by Django 5.2.11 on 2026-03-01 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('tech', '技術'), ('culture', '教養'), ('license', '資格')], max_length=20, unique=True, verbose_name='カテゴリー名')),
            ],
            options={
                'verbose_name': 'カテゴリー',
            },
        ),
        migrations.CreateModel(
            name='StudyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='学習タイトル')),
                ('description', models.TextField(blank=True, verbose_name='学習詳細')),
                ('study_date', models.DateField(verbose_name='学習日')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='学習時間（分）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='study.category', verbose_name='カテゴリー')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_records', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '学習記録',
                'ordering': ['-study_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp_type', models.CharField(choices=[('good', '👍'), ('great', '🔥'), ('nice', '💖')], max_length=10, verbose_name='スタンプ種類')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_stamps', to=settings.AUTH_USER_MODEL, verbose_name='送ったユーザー')),
                ('study_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stamps', to='study.studyrecord', verbose_name='学習記録')),
            ],
        ),
    ]
