# Generated by Django 5.2.11 on 2026-05-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('tech', '技術'), ('culture', '教養'), ('license', '資格'), ('curriculum', 'カリキュラム')], max_length=20, unique=True, verbose_name='カテゴリー名'),
        ),
    ]
