# Generated by Django 5.2.11 on 2026-05-21 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyrecord',
            name='achievements',
            field=models.TextField(blank=True, null=True, verbose_name='できるようになったこと'),
        ),
        migrations.AddField(
            model_name='studyrecord',
            name='questions',
            field=models.TextField(blank=True, null=True, verbose_name='問題点/疑問点'),
        ),
        migrations.AddField(
            model_name='studyrecord',
            name='solutions',
            field=models.TextField(blank=True, null=True, verbose_name='解決に向けて行ったこと'),
        ),
        migrations.AddField(
            model_name='studyrecord',
            name='struggles',
            field=models.TextField(blank=True, null=True, verbose_name='難しかったこと'),
        ),
    ]
