# Generated by Codex on 2026-05-26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_studyrecord_achievements_studyrecord_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyrecord',
            name='understanding',
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name='理解度',
            ),
        ),
    ]
