# Generated by Codex on 2026-05-26

from django.db import migrations


def add_curriculum_category(apps, schema_editor):
    Category = apps.get_model('study', 'Category')
    Category.objects.get_or_create(name='curriculum')


def remove_curriculum_category(apps, schema_editor):
    Category = apps.get_model('study', 'Category')
    Category.objects.filter(name='curriculum').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_studyrecord_understanding'),
    ]

    operations = [
        migrations.RunPython(add_curriculum_category, remove_curriculum_category),
    ]
