# Generated by Django 5.2.11 on 2026-07-14 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
        ('study', '0005_seed_curriculum_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyrecord',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_records', to='curriculum.curriculumchapter', verbose_name='対象章'),
        ),
        migrations.AddField(
            model_name='studyrecord',
            name='is_chapter_completion',
            field=models.BooleanField(default=False, verbose_name='章完了操作'),
        ),
    ]
