# Generated by Django 5.2.11 on 2026-07-18 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_seed_curriculum_master'),
        ('study', '0006_studyrecord_chapter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyrecord',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_records', to='curriculum.curriculumitem', verbose_name='対象小項目'),
        ),
    ]
